git:
  repo: 'mongodb/docs-node'
  remote:
    upstream: 'mongodb/docs-node'
    tools: 'mongodb/docs-tools'
project:
  name: 'node-driver'
  tag: 'node-driver'
  url: 'https://www.mongodb.com/docs/drivers/nodejs'
  title: 'Node Driver Manual'
  branched: true
version:
  release: 'upcoming'
  branch: 'master'
system:
  runstate:
    serial_sphinx: publish
  files:
    - 'intersphinx.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - 'push.yaml'
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
  - branch: master
    path: build/node-mongodb-native
    repository: https://github.com/mongodb/node-mongodb-native.git
paths:
  output: 'build'
  source: 'source-master'
  includes: 'source-master/includes'
  images: 'source-master/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'

...
