name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy mongodb-compat table
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'source/includes/mongodb-compatibility-table.rst'
        destination_repo: 'mongoKart/docs-shared'
        destination_folder: 'dbx/mongodb-compatibility-table-node.rst'
        user_email: 'mike.woofter@mongodb.com'
        user_name: 'mike.woofter'
        commit_message: 'Auto-import from docs-node'